CONST_SCREENWIDTH     = 1024
CONST_SCREENHEIGHT    = int(CONST_SCREENWIDTH * .56)
CONST_SCREENFACTOR    = 1
CONST_CAPTION         = "Platform"
CONST_FONTSTANDARD    = "Consolas"
CONST_FONTSIZE        = 14
CONST_PI              = 3.14159265358979323846264
CONST_PI180           = CONST_PI / 180
CONST_IPI180          = 180 / CONST_PI

CONST_TILESIZE        = 20

CONST_GRAVITY         = .25
CONST_MAXVELOCITY_Y   = 8
CONST_MAXVELOCITY_X   = 2.5
CONST_MAXVELOCITY     = 1000
CONST_FRICTION        = .08
CONST_FRICTIONNORMAL  = 1
CONST_FRICTIONMAG     = CONST_FRICTION * CONST_FRICTIONNORMAL

CONST_ROTATIONDECAY   = .985
CONST_MINROTATION     = .001
